language: go

before_install:
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: "Quick Build"
      os:
        - linux
        - osx
        - windows
      go: master
      script: go build
    - stage: "Quick Test"
      os:
        - linux
        - osx
        - windows
      go: master
      script: go test -race -cover
    - stage: "Full Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/
      os:
        - linux
        - osx
        - windows
      go:
        - "1.7.x"
        - "1.8.x"
        - "1.9.x"
        - "1.10.x"
        - "1.11.x"
        - "1.12.x"
      script: go build
    - stage: "Full Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/
      os:
        - linux
        - osx
        - windows
      go:
        - "1.7.x"
        - "1.8.x"
        - "1.9.x"
        - "1.10.x"
        - "1.11.x"
        - "1.12.x"
      script: go test -race -cover