language: go

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - stage: "Quick Build"
      go: master
      script: go build
    - stage: "Quick Test"
      go: master
      script: go test -race -cover
    - stage: "Full Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/
      go:
        - "1.7.x"
        - "1.8.x"
        - "1.9.x"
        - "1.10.x"
        - "1.11.x"
        - "1.12.x"
      script: go build
    - stage: "Full Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/
      go:
        - "1.7.x"
        - "1.8.x"
        - "1.9.x"
        - "1.10.x"
        - "1.11.x"
        - "1.12.x"
      script: go test -race -cover

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -race -cover
  - $GOPATH/bin/goveralls -service=travis-ci