language: go

jobs:
  include:
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.9.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.9.x
      script: go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.10.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.10.x
      script: go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.11.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.11.x
      script: go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race
    - stage: "Build"
      os: linux
      go: 1.12.x
      script: go build
    - stage: "Test"
      os: linux
      go: 1.12.x
      before_install: go get github.com/mattn/goveralls
      script: 
        - go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - stage: "Build"
      os: osx
      go: 1.12.x
      script: go build
    - stage: "Test"
      os: osx
      go: 1.12.x
      script: go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race
    # - stage: "Build"
    #   os: windows
    #   go: 1.12.x
    #   script: go build
    # - stage: "Test"
    #   os: windows
    #   go: 1.12.x
    #   script: go test . ./components/... ./internal/filesystem ./render/... ./scaffold/... -race