language: go

jobs:
  include:
    - stage: "Build"
      os: linux
      go: master
      script: go build
    - stage: "Test"
      os: linux
      go: master
      before_install: go get github.com/mattn/goveralls
      script: go test -race -cover; $GOPATH/bin/goveralls -service=travis-ci
    - stage: "Build"
      os: windows
      go: master
      script: go build
    - stage: "Test"
      os: windows
      go: master
      before_install: go get github.com/mattn/goveralls
      script: go test -race -cover; $GOPATH/bin/goveralls -service=travis-ci
    - stage: "Build"
      os: osx
      go: master
      script: go build
    - stage: "Test"
      os: osx
      go: master
      before_install: go get github.com/mattn/goveralls
      script: go test -race -cover; $GOPATH/bin/goveralls -service=travis-ci