language: go

os:
  - linux
  - osx
  - windows
 
go:
  - master
#  - "1.7.x"
#  - "1.8.x"
#  - "1.9.x"
#  - "1.10.x"
#  - "1.11.x"
#  - "1.12.x"




jobs:
  include:
    - stage: "Build"
      script: go build
    - stage: "Test"
      before_install: go get github.com/mattn/goveralls
      script: go test -race -cover; $GOPATH/bin/goveralls -service=travis-ci